In [2]:
from mido import MidiFile
import numpy as np
from pathlib import Path
import pickle

# Reading midi files and storing data

In [3]:
notes = []

time = 0.0
prev_time = 0.0


music_path = Path('./pop-music-collection/Pop_Music_Midi/')

for fil in music_path.glob('*.midi'):  #Iterating over all midi files
    mid = MidiFile(fil)  #Reading midi file
    print(fil)
    for msg in mid:
        time += msg.time
        if msg.type == 'note_on':  
        # including in training data only if recieved message is of type note_on
            note = msg.bytes() 
        # note message is in the form of [type, note, velocity]
        # taking only note and velocity
            note = note[1:]
            note.append(time-prev_time) 
            note.append(msg.channel)
            prev_time = time
            notes.append(note)
print(len(notes))
print(time)

pop-music-collection/Pop_Music_Midi/Put Your Records On - Chorus.midi
pop-music-collection/Pop_Music_Midi/The Great Escape - Verse.midi
pop-music-collection/Pop_Music_Midi/Love Me Harder ft The Weeknd - Pre Chorus.midi
pop-music-collection/Pop_Music_Midi/I Gotta Feeling - Chorus.midi
pop-music-collection/Pop_Music_Midi/I Want It That Way - Chorus.midi
pop-music-collection/Pop_Music_Midi/Girl On Fire - Chorus.midi
pop-music-collection/Pop_Music_Midi/Piano man - Bridge.midi
pop-music-collection/Pop_Music_Midi/Love Story - Chorus.midi
pop-music-collection/Pop_Music_Midi/All The Small Things - Verse.midi
pop-music-collection/Pop_Music_Midi/Genie in a Bottle - Verse.midi
pop-music-collection/Pop_Music_Midi/Timber - Verse.midi
pop-music-collection/Pop_Music_Midi/Barbie Girl - Chorus.midi
pop-music-collection/Pop_Music_Midi/Feel So Close - Chorus.midi
pop-music-collection/Pop_Music_Midi/Blank Space - Verse.midi
pop-music-collection/Pop_Music_Midi/Blank Space - Chorus.midi
pop-music-collection

# Data Normalization

In [4]:
notes = np.array(notes)
mean = np.mean(notes,axis=0)
print(mean)
sd = np.std(notes,axis=0)
print(sd)
notes = (notes[:]-mean)/sd
print(notes[:5])

[60.02926383 72.42930956  0.12544995  1.90964792]
[ 8.61605267 25.49014909  0.21616718  0.66362352]
[[-0.35158372  1.16008307 -0.58033764 -1.37072888]
 [ 0.46085328  0.3362354  -0.58033764  0.13614961]
 [ 0.80904057  0.3362354  -0.58033764  0.13614961]
 [-0.00339643  0.3362354  -0.58033764  0.13614961]
 [-1.39614558  0.3362354  -0.58033764  1.64302809]]


In [7]:
xtrain = []
ytrain = []
n_prev = 5
# n_prev notes to predict the (n_prev+1)th note
for i in range(len(notes)-n_prev):
    x = notes[i:i+n_prev]
    y = notes[i+n_prev]
    xtrain.append(x)
    ytrain.append(y)
# print(Y)
# save a seed to do prediction later
xtrain = np.array(xtrain)
ytrain = np.array(ytrain)

In [8]:
print(xtrain.shape)
print(ytrain.shape)

(21865, 5, 4)
(21865, 4)


In [9]:
with open('./xtrain.npy','wb') as f1:
    pickle.dump(xtrain,f1)
f1.close()

In [10]:
with open('./ytrain.npy','wb') as f2:
    pickle.dump(ytrain,f2)
f2.close()